# -*- coding: utf-8 -*-
"""Deep_learning_ex3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11wlPKv2RWP_sEPSWmkOd6Zw1HHEYMk7h
"""

from datetime import datetime
import pandas as pd
import zipfile
import matplotlib.pyplot as plt
import warnings
from scipy.special import rel_entr

warnings.filterwarnings('ignore', '.*do not.*', )

with zipfile.ZipFile("/content/drive/MyDrive/Colab Notebooks/compressed_dataset.csv.zip") as z:
    with z.open("compressed_dataset.csv") as f:
      df = pd.read_csv(f)

df["date_time"] = pd.to_datetime(df['timestamp'], unit="ms")
df['day'] = pd.to_datetime(df['date_time'].dt.strftime('%Y-%m-%d'))
df.head()

from scipy.stats import ks_2samp

df_wfo = df[df['viewer_type'] == 'WFO']
df_wfh = df[df['viewer_type'] == 'WFH']

ksdiff = []
ksdiff.append(ks_2samp(df_wfo['engagement'], df_wfh['engagement']).statistic)
ksdiff.append(ks_2samp(df_wfo['qoe'], df_wfh['qoe']).statistic)


plt.bar(['Engagement', 'QoE'], ksdiff, color ='maroon', width = 0.4)
plt.xlabel("Viewer Type")
plt.ylabel("Distribution differences")
plt.show()